const Map<String, String> ar = {
  'Home': 'الرئيسية',
  'My Orders': 'طلباتي',
  'article': 'مقالات',
  'More': 'المزيد',
  'search': 'ابحث عن مكان',
  'View': 'عرض الكل',
  'View All': 'عرض الكل',
  'Skip': 'تخطي',
  'Register': 'التسجيل',
  'Don’t have an account? ': 'ليس لديك حساب؟ ',
  'LOGIN': 'دخول',
  'Password required': 'كلمة المرور مطلوبة',
  'Password': 'كلمة المرور',
  'Phone': 'رقم الهاتف',
  'Phone required': 'رقم الهاتف مطلوب',
  'Login': 'تسجيل الدخول',
  'Phone number is wrong': 'رقم الهاتف خاطئ',
  'Password should have atleast 8 characters':'يجب أن تحتوي كلمة المرور على 8 أحرف على الأقل',
  'Enter a stronger password': 'أدخل كلمة مرور أقوى',
  'Your Name': 'الإسم بالكامل',
  'Your Name required': 'الإسم بالكامل مطلوب',
  'required': 'مطلوب *',
  'Sign Up': 'تسجيل',
  'By registering you agree to our': 'بالتسجيل فإنك توافق على',
  'Terms of Service': 'شروط الخدمة',
  ' Privacy Policy': ' سياسة الخصوصية ',
  'Re Password': 'كلمة المرور مرة أخري',
  'Email': 'البريد الألكتروني',
  'Email is wrong': 'البريد الألكتروني خاطئ',
  'Date of Birth': 'تاريخ الميلاد',
  'Passwords do not match': 'كلمتا المرور غير متطابقتان',
  'Lang': 'اللغة',
  'En': 'الإنجليزية',
  'Ar': 'العربية',
  'Edit Profile': 'تعديل الملف الشخصي',
  'Favorite products': 'المنتجات المفضلة',
  'number of Orders': 'عدد الطلبات',
  'number of prescriptions': 'عدد الروشتات',
  'Address': 'العناوين',
  'Notices': 'الإشعارات',
  'Settings': 'الإعدادات',
  'Logout': 'تسجيل الخروج',
  'Outher': 'أخري',
  'logout?': ' هل تريد تسجيل الخروج ؟ ',
  'cancel': 'إلغاء',
  'exit': 'خروج',
  'all': 'الكل',
  'filter': 'تصنيف',
  'Quantity': 'الكمية',
  'ok': 'نعم',
  'next': 'التالي',
  'start': 'إبدأ تجربتك الأن',
  'welcome': 'مرحبا بك',
  'login_desc': 'هذا النص مثال يمكن ان يستبدل بنص اخر',
  'phone_enter': 'من فضلك أدخل رقم الجوال',
  'send_code': 'إرسال الكود',
  'or': 'أو',
  'is_phone': 'لقد قمت بكتابة رقم',
  'confirm_phone': 'هل أنت متأكد من صحة الرقم ؟',
  'check_acc': 'التحقق من الحساب',
  'code_enter': 'الرجاء إدخال الكود المرسل على رقم الهاتف الخاص بك',
  'code_not_send': 'لم تستلم الكود بعد ؟',
  'code_send_agien': 'أعد إرسال الكود',
  'Done': 'تأكيد',
  'code error': 'الكود الذي أدخلتة خاطئ',
  'explore': 'إستكشف',
  'my reservations': 'حجوزاتي',
  'Arithmetic': 'حسابي',
  'duration': 'المدة : ',
  'hour': ' ساعة ',
  'new articals': 'أحدث المقالات',
  'trips_new': 'أحدث الرحلات',
  'About as': 'نبذه ',
  'company choose': 'إختيار الشركة',
  'trip_desc': 'تفاصيل الرحلة',
  'Program description': 'وصف البرنامج',
  'Program Rules': 'قواعد البرنامج',
  'Program Prohibitions': 'ممنوعات البرنامج',
  'Flight date': 'تاريخ الرحلة',
  'Select the date': 'حدد التاريخ',
  'The number of people': 'عدد الأشخاص',
  'adults': 'البالغين',
  'adults_age': '( العمر من 10 - 90 )',
  'kids': 'الأطفال',
  'kids_age': '( العمر أقل من 10 )',
  'Basic Add-ons': 'الإضافات الأساسية',
  'Payment method': 'طريقة الدفع',
  'credit card': 'بطاقة إئتمانية',
  'Credit card payment': 'الدفع بالبطاقة الأئتمانية',
  'cash payment': 'الدفع كاش',
  'Payment by cash': 'الدفع عن طريق الكاش',
  'choose trip date': 'حدد التاريخ',
  'choose paymentType': 'إختر طريقة الدفع',
  'companies': 'الشركات',
  'Completed booking': 'حجز مكتمل',
  'Complete the order': 'إتمام الطلب',
  'total + tax': 'الإجمالى + الضريبة',
  'Company Profile': 'نبذة عن الشركة',
  'Order details': 'تفاصيل الطلب',
  'the number': 'العدد',
  'the cost': 'التكلفة',
  'number of children': 'عدد الأطفال',
  'Adult': 'بالغ',
  'Child': 'طفل',
  'Add-ons': 'الأضافات',
  'add promocode': 'إضافة بروموكود',
  'Please enter the code': 'الرجاء أدخال البرموكود',
  'reservation confirmation': 'تأكيد الحجز',
  'Data completion': 'إستكمال البيانات',
  'Account holder information': 'بيانات صاحب الحساب',
  'Please enter the name': 'الرجاء أدخال الأسم',
  'Please enter age': 'الرجاء أدخال العمر',
  'age': 'العمر',
  'Please enter the ID number': 'الرجاء أدخال رقم الهوية',
  'ID number': 'رقم الهوية',
  'Please enter the site': 'الرجاء أدخال الموقع',
  'detect location': 'تحديد الموقع',
  'Location confirmation': 'تأكيد الموقع',
  'Adult facilities data': 'بيانات المرافق البالغ',
  'Childrens data': 'بيانات الأطفال',
  'Please select a nationality': 'الرجاء أختيار الجنسية',
  'Please enter the room number': 'الرجاء أدخال رقم الغرفة',
  'room number': 'رقم الغرفة',
  'Data of adult escorts is required': 'بيانات المرافقين البالغين مطلوبه',
  'Information of accompanying children is required':'بيانات المرافقين الأطفال مطلوبه',
  'null': 'حدث خطأ ما حاول مجددا',
  'payment': 'الدفع',
  'Your request has been sent successfully': 'تم إرسال طلبك بنجاح',
  'successfully sent':'تهانينا تم ارسال طلبك بنجاح , يمكنك متابعه الحجز من خلال خانة حجوزاتي',
  'Back to main': 'الرجوع للرئيسية',
  'My existing reservations': 'حجوزاتي القائمة',
  'My new bookings': 'حجوزاتي الجديدة',
  'My completed reservations': 'حجوزاتي المكتملة',
  'Flight Number': 'رقم الرحلة ',
  'cash': 'كاش',
  'visa': 'فيزا',
  'Booking details': 'تفاصيل الحجز',
  'Total': 'المجموع',
  'show more': 'إظهار المزيد',
  'flight rescheduled': 'معاد الرحلة',
  'people details': 'تفاصيل الأشخاص',
  'Nationality': 'الجنسية',
  'location': 'الموقع',
  'Order Summary': 'ملخص الطلب',
  'Value Added': 'القيمة المضافة',
  'change photo': 'تغيير الصورة',
  'The name': 'الإسم',
  'Notice': 'تنوية : ',
  'Notice_desc':'في حالة تعديل الرقم سيتم تسجيل الخروج وإرسال كود التفعيل للرقم الجديد',
  'camera': 'الكاميرا',
  'gallary': 'معرض الصور',
  'Favorite': 'المفضلة',
  'Portfolio': 'المحفظة',
  'Your current balance': 'رصيدك الحالي',
  'Wallet Charging': 'شحن المحفظة',
  'charging_value': 'أدخل القيمة',
  'The Value': 'القيمة',
  'Please enter The Value': 'الرجاء إدخال قيمة الشحن',
  'Connect with us': 'تواصل معنا',
  'whats up': 'الواتساب',
  'Sending a Message': 'إرسال رسالة',
  'send': 'إرسال',
  'the message': 'الرسالة',
  'Please write your message': 'الرجاء كتابة رسالتك',
  'who are we': 'من نحن',
  'About us': 'نبذه عنا',
  'Terms and Conditions': 'الشروط والأحكام',
  'Application language': 'لغة التطبيق',
  'app_lang_desc': 'هذا النص هو مثال يمكن ان يستبدل باي نص',
  'the currency': 'العملة',
  'Currency used': 'العملة المستخدمة',
  'Currency used Desc': 'هذا النص هو مثال يمكن ان يستبدل باي نص',
  'No notifications yet': 'لا توجد إشعارات حتي الأن',
  'No notifications yet Desc':'هذا النص مثال يمكن ان يستبدل باي نص أخر هذا النص مثال يمكن ان يستبدل باي نص أخر',
  'the site done': 'تم تحديد الموقع',
  'sale': 'خصم',
  'day:': 'اليوم : ',
  'Flight time': 'حدد الوقت',
  'Select the time': 'إختر الوقت',
  'from': 'من ',
  'to': ' إلي ',
  'Top Rated': 'الأعلى تقييما',
  'Lowest Rated': 'الأقل تقييما',
  'Highest Price': 'الأعلى سعرا',
  'lowest price': 'الأقل سعرا',
  'choose additions': 'إختر الأضافات',
  'name': 'الأسم',
  'promo is active': 'حصلت على خصم : ',
  'Your payment has been sent successfully': 'تم الدفع بنجاح',
  'Your no payment': 'لم يتم الدفع بنجاح',
  'error sent payment': 'حاول مره اخري',
  'Payment by wallet': 'يمكنك الدفع عن طريق المحفظة الأن',
  'no wallet price': 'تم تحويل الدفع الى كاش لعدم وجود رصيد كافي',
  'babys': 'الرضع',
  'babys_age': '(العمر أقل من سنتين)',
  'Baby': 'رضيع',
  'choose': 'إختر',
  'change price for nationality': 'السعر سيختلف على حسب الجنسية',
  'Price varies from': 'إختلف السعر إلي',
  'no articals now': 'لا يوجد مقالات الأن',
  'no trips now': 'لا يوجد رحلات الأن',
  'The number of add': 'عدد الأضافات',
  'wallet': 'المحفظة',
  'fish code': 'إنتهت صلاحية الرمز',
  'canceled': 'ملغي',
  'no reservations now': 'لا يوجد حجوزات الأن',
  'will be deducted': 'سيتم خصم',
  'From the value of the reservation': 'من قيمة الحجز',
  'Are you sure to cancel': 'هل أنت متأكد من الألغاء؟',
  'comment': 'تعليق',
  'Write a comment for the company': 'أكتب تعليق للشركة',
  'Please rate the company': 'من فضلك قيم الشركة',
  'Please rate the trip': 'من فضلك قيم الرحلة',
  'send rating': 'إرسال التقييم',
  'chosse rate': 'إختر التقييم المناسب',
  'choose persons': 'أختر عدد الأشخاص',
  'Pay again': 'ادفع مرة أخرى',
  'Connect with Google': 'تسجيل الدخول عبر جوجل',
  'Connect with Face': 'تسجيل الدخول باستخدام الفيسبوك',
  'Basic Add-ons no required': 'الإضافات المتاحة',
  'less text': 'أقراء أقل',
  'more text': 'أقراء المزيد',
  'please select a country': 'أختر الدولة',
  'your country': 'دولتك',
  'error_api': 'حدث خطأ ما .. حاول لاحقا',
  'no image selected': 'لم تقم بإختيار اي صورة',
  'Ask for notification status': 'تفعيل الأشعارات',
  'tax': 'الضريبة',
  'total': 'الإجمالي',
  'no companies now': 'لا يوجد عروض الأن',
  'pat_data': 'بيانات الدفع',
  'error': 'خطأ',
  'error desc': 'حدث خطأ ما نعمل على إصلاحة ..',
  'login with': 'تسجيل الخول بـ',
  'active_phone': 'تفعيل رقم الهاتف',
  'activation': 'تفعيل',
  'Enabled': 'مفعل',
  'vodafone': 'فوافون كاش',
  'vodafone cash payment': 'الدفع بفوافون كاش',
  'no company now': 'لا يوجد عروض الأن',
  'choose Basic Add-ons' : 'اختر واحد عالاقل من الاضافات الاساسيه',
  'no wallet this phone' : 'ليس لديك محفظه لهذا الرقم',
  'delete acc' : 'حـذف الحساب',
  'delete acc?' : 'هل تريد حذف الحساب؟',
  'not connected' : 'غير متصل بالشبكة',
  //
  'Time' : 'الوقت',
  // bird
  'started' : 'البدء',
  'Sign Up client' : 'مستخدم',
  'Sign Up Delivery' : 'مندوب توصيل',
  'Welcome to' : 'اهلا بك',
  'Already have an account?':'هل لديك حساب؟',
  'Verification code' : 'رمز التحقق',
  'Email address is not valid' : 'عنوان البريد الإلكتروني غير صالح',
  'Enter Your Email' : 'أدخل بريدك الإلكتروني',
  'Verify mail' : 'التحقق من البريد',
  'Code sent to' : 'تم إرسال الرمز إلى',
  'Im from validator' : 'كود التحقق خاطئ',
  'Verify' : 'التحقق',
  "Didn’t recieve code?" : 'لم تتلق الرمز؟',
  'Request' : 'اعاده الارسال',
  'Submit': 'التسجيل',
  'By clicking this it means that you are agree to' : 'بالضغط على هذا يعني أنك موافق على ذلك',
  'Terms & conditions' : 'الأحكام والشروط',
  'Enter Your Password' : 'ادخل رقمك السري',
  'First Name' : 'الاسم الأول',
  'Please enter First Name': 'الرجاء إدخال الاسم الأول',
  'Enter Your First Name' : 'أدخل اسمك الأول',
  'Create account' : 'إنشاء حساب',
  'agien' : 'حاول مره اخري',
  'termsCheck' : 'الرجاء الموافقه علي الشروط و الاحكام',
  'Forget your password?' : 'نسيت كلمة المرور؟',
  'Forget Pass' : 'استرجاع كلمه المرور',
  'change password' : 'تغيير كلمة المرور',
  'Confirm Password' : 'تأكيد كلمة المرور',
  'Enter Confirm Password' : 'أدخل تأكيد كلمة المرور',
  'New Password' : 'كلمة المرور الجديدة',
  'car type' : 'نوع السياره',
  'car color' : 'لون السياره',
  'car number' : 'رقم السياره',
  'car card' : 'صوره رخصه السياره',
  'isCar check' : 'ارفع صوره رخصه السياره',
  'isImage check' : 'ارفع صوره شخصيه',
  'Confirm location' : 'تأكيد الموقع',
  'Choose on map' : 'اختر على الخريطة',
  'Close' : 'اغلاق',
  'no address add' : 'لا يوجد عناوين مضافه',
  'Location name' : 'اسم الموقع',
  'Street' : 'شارع',
  'Flat' : 'الدور',
  'Building' : 'المبني',
  'Floor' : 'الشقه',
  'Add Location' : 'أضف الموقع',
  'Make this address default' : 'اجعل هذا العنوان افتراضيًا',
  'Good evening' : 'مساء الخير',
  'searchHome' : 'ابحث',
  'Delivering to' : 'التوصيل الى',
  'Stores' : 'متاجر',
  'Supermarket' : 'سوبر ماركت',
  'Restaurants' : 'مطاعم',
  'Pharmacies' : 'صيدليات',
  'Deliver Package' : 'توصيل طلب',
  'Deliver to a different location': 'تسليم إلى موقع مختلف',
  'Choose location on map':'اختر الموقع على الخريطة',
  'Edit' : 'تعديل',
  'Delete' : 'حذف',
  'Confirm' : 'تأكيد',
  'Edit location' : 'تعديل الموقع',
  'Account' : 'حسابي',
  'SAR' : 'ر.س',
  'Profile' : 'الملف الشخصي',
  'Share the app' : 'مشاركة التطبيق',
  'Coupons' : 'كوبونات',
  'Add Coupon' : 'أضف كوبون',
  'Orders rates' : 'تقيمات الطلبات',
  'Profile picture' : 'الصوره الشخصيه',
  'Profile info' : 'معلومات الشخصي',
  'Gender' : 'جنس',
  'Male' : 'ذكر',
  'Famele' : 'أنثى',
  'Address book':'دليل العناوين',
  'Add new adress' : '"إضافة عنوان جديد"',
  'Got it' : 'تأكيد',
  'Contact Us' : 'اتصل بنا',
  'Get in touch' : 'ابقى على تواصل',
  'Last Name' : 'اسم العائلة',
  'Go to Homepage' : 'اذهب إلى الصفحة الرئيسية',
  'Thank You!' : 'شكرًا لك!',
  'successfully submitted' : 'قدمت بنجاح',
  'Complain' : 'شكوى',
  'File a complain' : 'تقديم شكوى',
  'Languages' : 'اللغات',
  'Your complains' : 'شكاويك',
  'All restaurants' : 'جميع المطاعم',
  'Sort by' : 'ترتيب حسب',
  'Rating' : 'تقييم',
  'Under 30 mins' : 'أقل من 30 دقيقة',
  'Recommended' : 'مُستَحسَن',
  'A to Z' : 'من أ إلى ي',
  'High rating' : 'تقييم عالي',
  'Apply' : 'تأكيد',
  'Preparation time' : 'وقت التحضير',
  'Basic arrangement' : 'الترتيب الاساسي',
  'Reviews' : '( التعليقات )',
  'Delivery fee' : 'رسوم التوصيل',
  'Nearest branch' : 'أقرب فرع',
  'Opening time' : 'وقت مفتوح',
  'View Cart' : 'عرض السلة',
  'Fire Offers' : 'عروض النار',
  'Add to cart' : 'أضف إلى السلة',
  'Choose your meal' : 'اختر وجبتك',
  'Extras' : 'إضافات',
  'Optional' : 'اختياريا',
  'My Cart' : 'سلة التسوق الخاصة بي',
  'Items' : 'منتج',
  'Special requests' : 'طلبات خاصة',
  'Get a discount' : 'احصل على خصم',
  'Enter code' : 'ادخل الرمز',
  'Payment Summary' : 'ملخص الدفع',
  'Sub Total' : 'المجموع الفرعي',
  'Discount' : 'تخفيض',
  'Total amount': 'المبلغ الإجمالي',
  'Check out' : 'الدفع',
  'You have products in your cart from elsewhere' : 'لديك منتجات في السله من مكان اخر',
  'Are you sure you want to delete all basket items?' : 'هل انت متأكد انك تريد حذف جميع عناصر السلة ؟',
  'Service fees' : 'رسوم الخدمة',
  'My Cart empty' : 'سلة التسوق الخاصة بك فارغه',
  'Adress': 'العنوان',
  'Change': 'تغير',
  'Estimated time' : 'الوقت المقدر',
  'Different Credit/Debit Card' :'بطاقة ائتمان',
  'mins' : 'دقيقة',
  'Your package' : 'طلباتك',
  'Pick up adress' : 'التقاط العنوان',
  'Delivering adress' : 'عنوان التسليم',
  'Add pictures (Optional)' : 'إضافة صور (اختياري)',
  'Upload photos' : 'تحميل الصور',
  'Add notes': 'أضف ملاحظات',
  'This fare is based on the distance' :'تعتمد هذه الأجرة على المسافة ورسوم الخدمة',
  'Order now' : 'اطلب الان',
  'No current orders' :'لا توجد طلبات حاليه',
  'Previous orders': 'الطلبات السابقة',
  'Reorder' : 'إعادة',
  'No Previous orders' : 'لا توجد طلبات سابقة',
  'Order ID' : 'رقم الطلب',
  'Order Summery' : 'ملخص الطلب',
  'Grand Total'  :'المجموع الإجمالي',
  'Order is preparing and can’t be cancelled' : 'الطلب قيد الإعداد ولا يمكن إلغاؤه',
  'Arrival estimated time' : 'الوقت المقدر للوصول',
  'The rider arrived to the branch' : 'وصل المندوب إلى الفرع',
  'Track order' : 'تتبع الطلب',
  'Your delivery rider' : 'مندوب التسليم الخاص بك',
  'Delivery time' : 'موعد التسليم',
  'Rate your order' : 'قيم طلبك',
  'Delivering from' : 'التوصيل من',
  'Rates' : 'التقييمات',
  'No Rates' : 'لا يوجد تقييمات',
  'Notification' : 'إشعارات',
  'Current Order' : 'الطلبات الحاليه',
  'Previews Orders' : 'الطلبات السابقه',
  'No Previews orders' : 'لا توجد طلبات سابقه',
  'My coupons' : 'كوبونات',
  'No coupons' : 'لا يوجد كوبونات',
  'fnishAt' : 'سينتهي في',
  'copy' : 'نسخ',
  'Copied' : 'تم النسخ',
  'Applied' : 'مُطبَّق',
  'Type Here.....' : 'أكتب هنا.....',
  'No new orders' : 'لايوجد طلبات جديدة',
  'addres' : 'عنوان',
  'km' : 'كم',
  'order' : 'طلب',
  'Decline' : 'رفض',
  'Accept':'قبول',
  'Orders' : 'طلبات',
  'Arrived destination 1' : 'وصلت الوجهة 1',
  'Waiting for order' : 'في انتظار الطلب',
  'Start joury' :'التوجه للوجهه ٢',
  'Arrived destination 2' : 'وصلت الوجهة 2',
};
