const Map<String, String> en = {
  'Home': 'Home',
  'My Orders': 'My trips',
  'article': 'Article',
  'More': 'More',
  'search': 'Search',
  'View': 'View',
  'View All': 'View All',
  'Skip': 'Skip',
  'Register': 'Register',
  'Don’t have an account? ': 'Don’t have an account? ',
  'LOGIN': 'LOGIN',
  'Password required': 'Password required',
  'Password': 'Password',
  'Phone': 'Phone',
  'Phone required': 'Phone required',
  'Login': 'Sign In',
  'Phone number is wrong': 'Phone number is wrong',
  'Password should have atleast 8 characters':'Password should have atleast 8 characters',
  'Enter a stronger password': 'Enter a stronger password',
  'Your Name': 'Your Name',
  'Your Name required': 'Your Name required',
  'required': 'required *',
  'Sign Up': 'Sign Up',
  'By registering you agree to our': 'By registering you agree to our',
  'Terms of Service': 'Terms of Service',
  ' Privacy Policy': ' Privacy Policy ',
  'Re Password': 'Re Password',
  'Email': 'Email',
  'Email is wrong': 'Email is wrong',
  'Date of Birth': 'Date of Birth',
  'Passwords do not match': 'Passwords do not match',
  'Lang': 'Language',
  'En': 'English',
  'Ar': 'Arabic',
  'Edit Profile': 'Edit Profile',
  'Favorite products': 'Favorite products',
  'number of Orders': 'Number of Orders',
  'number of prescriptions': 'Nmber of prescriptions',
  'Address': 'Address',
  'Notices': 'Notices',
  'Settings': 'Settings',
  'Logout': 'Logout',
  'Outher': 'Outher',
  'logout?': ' Do you want to log out? ',
  'cancel': 'Cancel',
  'exit': 'Exit',
  'all': 'ALL',
  'filter': 'filter',
  'Quantity': 'Quantity',
  'ok': 'yes',
  'next': 'next',
  'start': 'Start your experience now',
  'welcome': 'welcome',
  'login_desc': 'This example text can be replaced by another text',
  'phone_enter': 'Please enter your mobile number',
  'send_code': 'send code',
  'or': 'or',
  'is_phone': 'You typed a number',
  'confirm_phone': 'Are you sure the number is correct?',
  'check_acc': 'check account',
  'code_enter': 'Please enter the code sent to your phone number',
  'code_not_send': 'You havent received the code yet?',
  'code_send_agien': 'resend code',
  'Done': 'confirm',
  'code error': 'The code you entered is wrong',
  'explore': 'Explore',
  'my reservations': 'Reservations',
  'Arithmetic': 'My account',
  'duration': 'duration :',
  'hour': 'hour',
  'new articals': 'latest articles',
  'trips_new': 'recent trips',
  'About as': 'About ',
  'company choose': 'company choose',
  'trip_desc': 'trip details',
  'Program description': 'Program description',
  'Program Rules': 'Program Rules',
  'Program Prohibitions': 'Prohibitions',
  'Flight date': 'Trip date',
  'Select the date': 'Select the date',
  'The number of people': 'number of people',
  'adults': 'adults',
  'adults_age': '(age 10-90 )',
  'kids': 'kids',
  'kids_age': '(age less than 10 )',
  'Basic Add-ons': 'Basic Add-ons',
  'Payment method': 'Payment method',
  'credit card': 'credit card',
  'Credit card payment': 'Credit card payment',
  'cash payment': 'cash payment',
  'Payment by cash': 'Payment by cash',
  'choose trip date': 'select the date',
  'choose paymentType': 'choose payment method',
  'companies': 'companies',
  'Completed booking': 'Completed booking',
  'Complete the order': 'Complete the order',
  'total + tax': 'total + tax',
  'Company Profile': 'Company Profile',
  'Order details': 'Order details',
  'the number': 'the number',
  'the cost': 'the cost',
  'number of children': 'number of children',
  'Adult': 'adult',
  'Child': 'child',
  'Add-ons': 'Add-ons',
  'add promocode': 'add promocode',
  'Please enter the code': 'Please enter the code',
  'reservation confirmation': 'reservation confirmation',
  'Data completion': 'Data completion',
  'Account holder information': 'Account holder information',
  'Please enter the name': 'Please enter the name',
  'Please enter age': 'Please enter age',
  'age': 'age',
  'Please enter the ID number': 'Please enter the ID number',
  'ID number': 'ID number',
  'Please enter the site': 'Please enter the site',
  'detect location': 'detect location',
  'Location confirmation': 'Location confirmation',
  'Adult facilities data': 'Adult facilities data',
  'Childrens data': 'Childrens data',
  'Please select a nationality': 'Please select a nationality',
  'Please enter the room number': 'Please enter the room number',
  'room number': 'room number',
  'Data of adult escorts is required': 'Data of adult escorts is required',
  'Information of accompanying children is required':'Child escort data is required',
  'null': 'Something went wrong, try again',
  'payment': 'payment',
  'Your request has been sent successfully':'Your request has been sent successfully',
  'successfully sent':'Congratulations, your request has been successfully sent, you can follow up on your booking through the My Bookings field',
  'Back to main': 'Back to main',
  'My existing reservations': 'Existing',
  'My new bookings': 'New Bookings',
  'My completed reservations': 'Completed',
  'Flight Number': 'Trip number',
  'cash': 'cash',
  'visa': 'visa',
  'Booking details': 'Booking details',
  'Total': 'total',
  'show more': 'show more',
  'flight rescheduled': 'trip rescheduled',
  'people details': 'people details',
  'Nationality': 'Nationality',
  'location': 'location',
  'Order Summary': 'Order Summary',
  'Value Added': 'Value Added',
  'change photo': 'change photo',
  'The name': 'The name',
  'Notice': 'Notice :',
  'Notice_desc':'In case the number is modified, the checkout will be logged and the activation code will be sent to the new number.',
  'camera': 'camera',
  'gallarry': 'gallery',
  'Favorite': 'Favorite',
  'Portfolio': 'Portfolio',
  'Your current balance': 'Your current balance',
  'Wallet Charging': 'Wallet Charging',
  'charging_value': 'Enter the value',
  'The Value': 'The Value',
  'Please enter The Value': 'Please enter the shipping value',
  'Connect with us': 'Connect with us',
  'whats up': 'whats up',
  'Sending a Message': 'Sending a Message',
  'send': 'send',
  'the message': 'the message',
  'Please write your message': 'Please write your message',
  'who are we': 'who are we',
  'About us': 'About us',
  'Terms and Conditions': 'Terms and Conditions',
  'Application language': 'Application language',
  'app_lang_desc': 'This text is an example that can be replaced with any text',
  'the currency': 'the currency',
  'Currency used': 'Currency used',
  'Currency used Desc':'This text is an example that can be replaced with any text',
  'No notifications yet': 'No notifications',
  'No notifications yet Desc':'This example text can be replaced by any other text This example text can be replaced by any other text',
  'the site done': 'Location selected',
  'sale': 'sale',
  'day:': 'Today : ',
  'Flight time': 'set time',
  'Select the time': 'Choose the time',
  'from': 'from ',
  'to': ' to ',
  'Top Rated': 'Top Rated',
  'Lowest Rated': 'Lowest Rated',
  'Highest Price': 'Most price',
  'lowest price': 'lowest price',
  'choose additions': 'Choose add-ons',
  'name': 'The name',
  'promo is active': 'I got a discount: ',
  'Your payment has been sent successfully': 'Payment completed successfully',
  'Your no payment': 'Payment not completed successfully',
  'error sent payment':'Try again',
  'Payment by wallet': 'You can pay by wallet now',
  'no wallet price':'Payment has been transferred to cash due to insufficient balance',
  'babys': 'infants',
  'babys_age': '(age is less than 2 years)',
  'Baby': 'infant',
  'choose': 'Choose',
  'change price for nationality':'The price will vary according to nationality',
  'Price varies from': 'The price is different',
  'no articals now': 'There are no articles for now',
  'no trips now': 'There are no trips now',
  'The number of add': 'number of additions',
  'wallet': 'Wallet',
  'fish code': 'Code has expired',
  'canceled': 'canceled',
  'no reservations now': 'No reservations now',
  'will be deducted': 'will be deducted',
  'From the value of the reservation': 'From the value of the reservation',
  'Are you sure to cancel': 'Are you sure to cancel?',
  'comment': 'Comment',
  'Write a comment for the company': 'Write a comment for the company',
  'Please rate the company': 'Please rate the company',
  'Please rate the trip': 'Please rate the trip',
  'send rating': 'Submit rating',
  'chosse rate': 'Choose the appropriate rating',
  'choose persons': 'Choose the number of people',
  'Pay again': 'Pay again',
  'Connect with Google': 'Login with Google',
  'Connect with Face': 'Login with Facebook',
  'Basic Add-ons no required': 'Available add-ons',
  'less text': 'read less',
  'more text': 'read more',
  'please select a country': 'Select the country',
  'your country': 'your country',
  'error_api': 'Something went wrong..try later',
  'no image selected': 'no image selected',
  'Ask for notification status': 'Activate notifications',
  'tax': 'tax',
  'total': 'total',
  'no companies now': 'no companies now',
  'pat_data': 'Payment data',
  'error': 'error',
  'error desc': 'Something went wrong we are working on..',
  'login with': 'Sign in with',
  'active_phone': 'Activate the phone number',
  'activation': 'Activation',
  'Enabled': 'Enabled',
  'vodafone': 'vodafone cash',
  'vodafone cash payment': 'Pay with vodafone Cash',
  'no company now': 'There are no offers now',
  'choose Basic Add-ons' : 'Choose at least one of the basic add-ons',
  'no wallet this phone' : 'You do not have a wallet for this number',
  'delete acc' : 'delete account',
  'delete acc?' : 'Do you want to delete the account?',
  'not connected' : 'not connected',
  'Time' : 'Time',

  // bird
  'started' : 'Get started',
  // bird
  'Sign Up client' : 'مستخدم',
  'Sign Up Delivery' : 'Sign Up Delivery',
  'Welcome to' : 'اهلا بك',
  'Already have an account?':'هل لديك حساب؟',
  'Verification code' : 'رمز التحقق',
  'Email address is not valid' : 'عنوان البريد الإلكتروني غير صالح',
  'Enter Your Email' : 'أدخل بريدك الإلكتروني',
  'Verify mail' : 'التحقق من البريد',
  'Code sent to' : 'تم إرسال الرمز إلى',
  'Im from validator' : 'كود التحقق خاطئ',
  'Verify' : 'التحقق',
  "Didn’t recieve code?" : 'لم تتلق الرمز؟',
  'Request' : 'اعاده الارسال',
  'Submit': 'التسجيل',
  'By clicking this it means that you are agree to' : 'بالضغط على هذا يعني أنك موافق على ذلك',
  'Terms & conditions' : 'الأحكام والشروط',
  'Enter Your Password' : 'ادخل رقمك السري',
  'First Name' : 'الاسم الأول',
  'Please enter First Name': 'الرجاء إدخال الاسم الأول',
  'Enter Your First Name' : 'أدخل اسمك الأول',
  'Create account' : 'إنشاء حساب',
  'agien' : 'حاول مره اخري',
  'termsCheck' : 'الرجاء الموافقه علي الشروط و الاحكام',
  'Forget your password?' : 'نسيت كلمة المرور؟',
  'Forget Pass' : 'استرجاع كلمه المرور',
  'change password' : 'تغيير كلمة المرور',
  'Confirm Password' : 'تأكيد كلمة المرور',
  'Enter Confirm Password' : 'أدخل تأكيد كلمة المرور',
  'New Password' : 'كلمة المرور الجديدة',
  'car type' : 'نوع السياره',
  'car color' : 'لون السياره',
  'car number' : 'رقم السياره',
  'car card' : 'صوره رخصه السياره',
  'isCar check' : 'ارفع صوره رخصه السياره',
  'isImage check' : 'ارفع صوره شخصيه',
  'Confirm location' : 'تأكيد الموقع',
  'Choose on map' : 'اختر على الخريطة',
  'Close' : 'اغلاق',
  'no address add' : 'لا يوجد عناوين مضافه',
  'Location name' : 'اسم الموقع',
  'Street' : 'شارع',
  'Flat' : 'الدور',
  'Building' : 'المبني',
  'Floor' : 'الشقه',
  'Add Location' : 'أضف الموقع',
  'Make this address default' : 'اجعل هذا العنوان افتراضيًا',
  'Good evening' : 'مساء الخير',
  'searchHome' : 'ابحث',
  'Delivering to' : 'Delivering to',
  'Stores' : 'Stores',
  'Supermarket' : 'Supermarket',
  'Restaurants' : 'Restaurants',
  'Pharmacies' : 'Pharmacies',
  'Deliver Package' : 'Deliver Package',
  'Deliver to a different location': 'تسليم إلى موقع مختلف',
  'Choose location on map':'اختر الموقع على الخريطة',
  'Edit' : 'تعديل',
  'Delete' : 'حذف',
  'Confirm' : 'تأكيد',
  'Edit location' : 'تعديل الموقع',
  'Account' : 'حسابي',
  'SAR' : 'ر.س',
  'Profile' : 'الملف الشخصي',
  'Share the app' : 'مشاركة التطبيق',
  'Coupons' : 'كوبونات',
  'Add Coupon' : 'أضف كوبون',
  'Orders rates' : 'تقيمات الطلبات',
  'Profile picture' : 'الصوره الشخصيه',
  'Profile info' : 'معلومات الشخصي',
  'Gender' : 'جنس',
  'Male' : 'ذكر',
  'Famele' : 'أنثى',
  'Address book':'دليل العناوين',
  'Add new adress' : '"إضافة عنوان جديد"',
  'Got it' : 'تأكيد',
  'Contact Us' : 'اتصل بنا',
  'Get in touch' : 'ابقى على تواصل',
  'Last Name' : 'اسم العائلة',
  'Go to Homepage' : 'اذهب إلى الصفحة الرئيسية',
  'Thank You!' : 'شكرًا لك!',
  'successfully submitted' : 'قدمت بنجاح',
  'Complain' : 'شكوى',
  'File a complain' : 'تقديم شكوى',
  'Languages' : 'اللغات',
  'Your complains' : 'شكاويك'
};
