// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ7GwG8MN9XJ2VZ8nUfmatLlKFnXcLbYY',
    appId: '1:736086961486:ios:53082645cfe4afe42c821f',
    messagingSenderId: '736086961486',
    projectId: 'bird-776ab',
    databaseURL: 'https://bird-776ab-default-rtdb.firebaseio.com',
    storageBucket: 'bird-776ab.appspot.com',
    iosBundleId: 'com.ocoda.birdsoand',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy5sSCIS5SUppKFjGiuLZEyRid_qIGmxQ',
    appId: '1:736086961486:android:a6cdf6a6ba135eeb2c821f',
    messagingSenderId: '736086961486',
    projectId: 'bird-776ab',
    databaseURL: 'https://bird-776ab-default-rtdb.firebaseio.com',
    storageBucket: 'bird-776ab.appspot.com',
  );

}